In [1]:
import io
import os

import pandas as pd

from azure.storage.blob import BlobServiceClient, BlobClient
from azure.core.exceptions import ResourceNotFoundError

def blob_to_df(blob_name):
    # Connection string to your Azure Storage account
    connection_string = os.environ['AZURE_STORAGE_CONNECTION_STRING']
    container_name = os.environ['AZURE_STORAGE_CONTAINER']

    # Create a blob client
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

    try:
        blob_data = blob_client.download_blob().readall()
        return pd.read_csv(io.BytesIO(blob_data))
    except ResourceNotFoundError:
        return pd.DataFrame()
    
df = blob_to_df('goodreads_ratings.csv')
df

,ISBN,Title,Scraped Rating Value,Scraped Rating Count,Scraped Review Count,Data Retrieved,Book Id
0,"=""0593309715""","Defiant (Skyward, #4)",4.50,1270,206,2023-11-26 21:32:20,NaN
1,"=""1596065443""",The Willful Princess and the Piebald Prince,4.03,8657,859,2023-11-26 21:32:29,NaN
2,"=""0007273770""",The Inheritance,3.98,4803,459,2023-11-26 21:32:39,NaN
3,"=""""","Fool's Assassin (The Fitz and the Fool, #1)",4.41,53917,3543,2023-11-26 21:33:01,NaN
4,"=""0062116851""","Blood of Dragons (Rain Wild Chronicles, #4)",4.17,30367,1778,2023-11-26 21:33:19,NaN
...,...,...,...,...,...,...,...
259,"=""031639081X""",Sharp Ends,4.13,18924,1516,2023-12-02 17:05:30,26030742.0
260,"=""159116057X""","One Piece, Volume 2: Buggy the Clown",4.36,22184,1062,2023-12-02 17:05:35,364956.0
261,"=""1569319014""","One Piece, Volume 1: Romance Dawn (One Piece, #1)",4.47,134743,3012,2023-12-02 17:05:41,1237398.0
262,"=""0743411692""","Xenos (Eisenhorn, #1)",4.16,8753,586,2023-12-02 17:05:44,1009259.0
263,"=""0316214442""",Red Country,4.31,49843,3026,2023-12-02 17:05:47,13521459.0